### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by ghost** [Jougito/Staff-Changer#1]
Can you make an english translation?

Thank you in advance.

**Comment by Jougito** [comment]
Yeah, I'm working on a translation system for all scripts. As soon as it is ready and tested, the commit will be uploaded ^^

**Comment by Jougito** [comment]
Translation system implemented - 5f9b8d2

To download the latest version go [here](https://github.com/Jougito/Staff-Changer/releases/latest) and download the zip file `Staff_Changer-v1.0.2.zip`.

I also leave you [here](https://discord.com/invite/74gVSf7) the Discord in case you have doubts or want to take a look at the things that are being done.

Thank you
